# TP 3 - Dynamic programming

## 1 - Treasure maze

Let's create a maze.

- Your robot can only go towards east and south (from top left).
- On each case, it can collect some reward.
- Find the path with maximum total reward.

In [1]:
import numpy as np

rewards = np.random.randint(20, size=(5, 6))
N, M = rewards.shape
print(rewards)

[[ 8  9 14  1 12 14]
 [ 6 16  5  4 10 18]
 [ 7  1  2  8 19 16]
 [ 5  4  0 14  7  3]
 [ 1  3  3 16  1  3]]


Is the greedy strategy optimal?

After you've found the maximum total reward, please show the path your robot should take.

In [2]:
best = np.zeros((N, M))
prec = [['.' for _ in range(M)] for _ in range(N)]

# Your code here

## 2 - Shortest paths

In [3]:
weights = np.random.randint(20, size=(5, 5))
print(weights)

[[15  6  2  4  4]
 [18 19  8  2 14]
 [10 14 10 17 14]
 [ 2  8 18 13 13]
 [ 1 12 13  6 18]]


Compute the shortest path between any pair of nodes. For that we will frame the **principle of optimality**.

## Notations

- $s$ is a state, $a$ an action, $r$ a reward

You cannot control the environment:

- $p(s', r|s, a)$ is the probability to land in state $s'$ with reward $r$ when choosing action $a$ from state $s$.

But you can control the agent:

- $\pi(a|s)$ is the probability that the agent chooses action $a$ from state $s$.

Useful quantities:

- $S_t$ is the state at time $t$, $A_t$ the action at time $t$ landing in state $S_{t + 1}$ with reward $R_{t + 1}$
- $\def\E{\mathbb{E}}\gamma$ is a *discount* factor for future rewards
- $G_t$ is the *discounted return*: $G_t = R_{t + 1} + \gamma R_{t + 2} + \gamma^2 R_{t + 3} + \ldots = \sum_{k = 0}^\infty \gamma^k R_{t + k + 1} = \sum_{k = t + 1}^T \gamma^{k - t - 1} R_k$ where $T$ can be $\infty$.
- The *value function $v_\pi$ for policy $\pi$* : $v_\pi(s) = \E_\pi[G_t|S_t = s]$
- The *action-value function $q_\pi$ for policy $\pi$* : $q_\pi(s, a) = \E_\pi[G_t|S_t = s, A_t = a]$

## 3 - Gridworld

Let's imagine a grid where the following rules occur:

- Movements against the walls give a reward of $-1$
- Walking on $(1, 4)$ gives a reward of $10$ and teleports to $(1, 0)$
- Walking on $(3, 4)$ gives a reward of $5$ and teleports to $(3, 2)$
- Every other movement gives no reward.

In [4]:
actions = [(0, 1), (1, 0), (0, -1), (-1, 0)]
states = {(x, y) for x in range(5) for y in range(5)}
policy = {s: [0.25, 0.25, 0.25, 0.25] for s in states}
value = {s: 0 for s in states}

def next_(s, a):
    if s == (1, 4):
        return 10, (1, 0)
    if s == (3, 4):
        return 5, (3, 2)
    x = s[0] + actions[a][0]
    y = s[1] + actions[a][1]
    if 0 <= x < 5 and 0 <= y < 5:
        return 0, (x, y)
    else:
        return -1, s

def plot(policy, value):
    for y in range(4, -1, -1):
        print(np.round([value[x, y] for x in range(5)], 1))
    for y in range(4, -1, -1):
        print(''.join(['^>v<'[np.argmax(policy[(x, y)])] for x in range(5)]))

GAMMA = 0.9

plot(policy, value)

[0 0 0 0 0]
[0 0 0 0 0]
[0 0 0 0 0]
[0 0 0 0 0]
[0 0 0 0 0]
^^^^^
^^^^^
^^^^^
^^^^^
^^^^^


### Policy evaluation

Given the recursive expression $$v_\pi(s) = \sum_a \pi(a|s) \sum_{s', r} p(s', r|s, a) [r + \gamma v_\pi(s')]$$

Compute the state value function $v_\pi$ for the equiprobable random policy.

In [ ]:
def eval_policy(policy, NB_STEPS=100):
    # Your code here
    return value

value = eval_policy(policy)

### Policy improvement

Given this new value function, we can improve our policy: $$ \DeclareMathOperator*{\argmax}{argmax} \pi'(s) = \argmax_a q(s, a) = \argmax_a \sum_{s', r} p(s', r|s, a) [r + \gamma v_\pi(s)]. $$

In [ ]:
def policy_improvement_is_stable(policy, value):
    # Your code here
    return is_stable  # Should return True if the policy did not change at all

policy_improvement_is_stable(policy, value)
plot(policy, value)

Until stability, alternatively do policy evaluation then policy improvement. What is the best policy?

In [ ]:
def policy_iteration(policy, MAX_STEPS=30):
    pass

nb_steps, policy, value = policy_iteration(policy)
print('Converged in', nb_steps, 'steps')
plot(policy, value)